### ISSUE TITLE
epoch and out of memory problem

### ISSUE THREAD

**Issue by ingbeeedd** [remmarp/PaDiM-TF#1]
I'm going to apply an augmentation to my dataset, not Mvtec, to spin several epochs. Since there are many batches, the out of memory phenomenon occurred when out went up to RAM. How can I get a mean, variation?

```python
out = []
    for x, _, _ in train_set:
        l1, l2, l3 = net(x)
        _out = tf.reshape(embedding_concat(embedding_concat(l1, l2), l3), (batch_size, h * w, c))  # (b, h x w, c)
        out.append(_out.numpy())
```

**Comment by remmarp** [comment]
PaDiM collects tons of intermediate outputs to calculate covariance. 

What size of RAM do you use? 
If your RAM is not enough, google colab (especially colab pro) could be an alternative.
